model:
  fuser:
    type: ConvFuser
    in_channels: [80, 256]
    out_channels: 256
  # fuser:
  #   type: DynamicFuser
  #   in_channels: [80, 256]
  #   out_channels: 256
  # attention:
  #   type: DFM
  #   in_channels: 256
  #   out_channels: 256
  # attention:
  #   type: ECA
  #   channels: 256
  # attention:
  #   type: CBAM
  #   in_channels: 256
  attention:
    type: CA
    in_channels: 256
    out_channels: 256

