model:
  type: BEVFusion
  encoders: null
  fuser: null
  attention: null
  decoder: null
  heads: null  

  aux_flag: true  #TODO Camera auxiliary training branch
  aux_decoder:
    backbone:
      type: GeneralizedResNet
      in_channels: 80
      blocks:
        - [2, 128, 2]
        - [2, 256, 2]
        - [2, 512, 1]
    neck:
      type: LSSFPN
      in_indices: [-1, 0] # 使用resnet最后一层和第一层
      in_channels: [512, 128]
      out_channels: 256
      scale_factor: 2 # 上采样因子
  aux_heads: 
    object:
      type: CenterHead
      in_channels: 256
      train_cfg:
        point_cloud_range: ${point_cloud_range}
        grid_size:  [1440, 1440, 41]   #[1024, 1024, 1]
        voxel_size: ${voxel_size}
        out_size_factor: 8
        dense_reg: 1
        gaussian_overlap: 0.1
        max_objs: 500
        min_radius: 2
        code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2]
      test_cfg:
        post_center_limit_range: [-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]
        max_per_img: 500
        max_pool_nms: false
        min_radius: [0.175, 4]
        score_threshold: 0.1
        out_size_factor: 8
        voxel_size: ${voxel_size[:2]}
        pre_max_size: 1000
        post_max_size: 83
        nms_thr: 0.2
        nms_type:
          - rotate
          - circle
        nms_scale:
          - [2.5]
          - [1.0]
      tasks:
        - ["meteor"]
        - ["platform"]
      common_heads:
        reg: [2, 2]
        height: [1, 2]
        dim: [3, 2]
        rot: [2, 2]
        vel: [2, 2]
      share_conv_channel: 64
      bbox_coder:
        type: CenterPointBBoxCoder
        pc_range: ${point_cloud_range}
        post_center_range: [-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]
        max_num: 500
        score_threshold: 0.1
        out_size_factor: 8
        voxel_size: ${voxel_size[:2]}
        code_size: 9
      separate_head:
        type: SeparateHead
        init_bias: -2.19
        final_kernel: 3
      loss_cls:
        type: GaussianFocalLoss
        reduction: mean
      loss_bbox:
        type: L1Loss
        reduction: mean
        loss_weight: 0.25
      norm_bbox: true

